[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
auto_detect_solc = false
optimizer = true
optimizer_runs = 10000
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

